version: '3.0'
services:
  rasa:
#   image: rasa/rasa:latest
    build: .
    image: metul/rasaserver
    ports:
      - 5005:5005
#    volumes:
#      - ./:/app
    command: 
      - run
      - -m 
      - models 
      - --enable-api 
      - --cors 
      - "*"
  action-server:
#    image: rasa/rasa-sdk:3.5.1
    build: actions
    image:  metul/rasaaction
#    volumes:
 #     - ./actions:/app/actions
    ports:
      - 5055:5055
    expose: 
      - 5055
  website:
#    image: nginx:alpine
    build: webpages
    image: metul/rasaweb
#    volumes:
#     - ./webpages:/usr/share/nginx/html
    ports:
      - 8080:80
