name: chatbot application deployment
on:
  push
jobs:
  deploy:
    name: Deploy yamls to azure vm
    runs-on: ubuntu-latest
    steps:
      - name: Get all changed .js file(s) or any file in the static folder excluding the docs folder
        id: changed-files-excluded
        uses: tj-actions/changed-files@v36
        with:
          files: |
            models
            domain.yml
      - uses: actions/checkout@v2
      - name: Deploy
        if: steps.changed-files-excluded.outputs.any_changed == 'false'
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: >-  
            -rltgoDzvO
            --exclude='.github'
            --exclude='.git'
            --exclude='.keras'
            --exclude='.config'
            --exclude='.gitignore'
            --exclude='Text.txt'
            --exclude='tempworkflow.txt'
            --exclude='graph.html'
            --exclude='README.md'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/azureuser/pipelinetest/
          SCRIPT_BEFORE: |
            cd pipelinetest/
            docker compose down
            rm -r /home/azureuser/pipelinetest/previous_version_copy/models/*
            rsync -av --progress /home/azureuser/pipelinetest/ /home/azureuser/pipelinetest/previous_version_copy/ --exclude previous_version_copy
            rm -r /home/azureuser/pipelinetest/models/*
          SCRIPT_AFTER: |
            cd pipelinetest/
            docker compose up -d