name: chatbot application deployment
on:
  push

jobs:
  dockercompose:
    name: docker compose
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: metul/rasaserver
          - dockerfile: ./actions/Dockerfile
            image: metul/rasaaction
          - dockerfile: ./webpages/Dockerfile
            image: metul/rasaweb
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}     
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}
      - name: build and push image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          data_validate: true
          rasa_train: true
          cross_validation: true
          #rasa_test: true
          #test_type: all
         # publish_summary: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload model
        uses: actions/upload-artifact@v3.1.2
        with:
          name: model
          path: models

  deploy:
    name: Deploy yamls to azure vm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: >-  
            -rltgoDzvO
            --exclude='.github'
            --exclude='.git'
            --exclude='.keras'
            --exclude='.config'
            --exclude='models/'
            --exclude='actions/'
            --exclude='.gitignore'
            --exclude='Text.txt'
            --exclude='tempworkflow.txt'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/azureuser/pipelinetest/
