name: train and test rasa chatbot

on:
  push

jobs:
  dockercompose:
    name: docker compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the images
        run: docker-compose build 
      - name: push the images
        run: docker-compose push
      - name: create containers
        run: docker-compose up -d
#      - name: run containers
  #      run: docker-compose start
      - name: Test
        run: docker run --network container:rasachatbot_website_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          data_validate: true
          rasa_train: true
          cross_validation: true
          #rasa_test: true
          #test_type: all
         # publish_summary: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload model
        uses: actions/upload-artifact@v3.1.2
        with:
          name: model
          path: models
  push_to_registry:
    needs: training-testing
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: metul/rasaimage
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
